// Ethiopian Banks List
export const ethiopianBanks = [
  "Commercial Bank of Ethiopia (CBE)",
  "Awash Bank",
  "Dashen Bank",
  "Bank of Abyssinia",
  "Wegagen Bank",
  "United Bank",
  "Nib International Bank",
  "Cooperative Bank of Oromia",
  "Lion International Bank",
  "Oromia International Bank",
  "Zemen Bank",
  "Buna International Bank",
  "Berhan International Bank",
  "Abay Bank",
  "Addis International Bank",
  "Debub Global Bank",
  "Enat Bank",
  "Gadaa Bank",
  "Goh Betoch Bank",
  "Hijra Bank",
  "Shabelle Bank",
  "Siinqee Bank",
  "Tsedey Bank",
  "Tsehay Bank",
  "ZamZam Bank",
] as const;

